### ISSUE TITLE
getTabId is not defined

### ISSUE THREAD

**Issue by GuyKh** [eljeffeg/SmartCopy#125]
After V3 migration (https://github.com/eljeffeg/SmartCopy/pull/124) - cc @mamsterla 
getting:

```
Error handling response: ReferenceError: getTabId is not defined
    at getPageCode (chrome-extension://ofikakkdpjlipbnhbfloclbkcabdhjah/popup.js:799:33)
    at Object.parseData (chrome-extension://ofikakkdpjlipbnhbfloclbkcabdhjah/collections/findagrave.js:17:13)
    at loginProcess (chrome-extension://ofikakkdpjlipbnhbfloclbkcabdhjah/popup.js:204:28)
    at chrome-extension://ofikakkdpjlipbnhbfloclbkcabdhjah/popup.js:873:9
```

pointing to [this](https://github.com/eljeffeg/SmartCopy/blob/master/popup.js#L799)

**Comment by mamsterla** [comment]
I will take a look at that.  Thanks.  Adding Jeff G for visibility.

**Comment by mamsterla** [comment]
I just pushed changes on that branch to address the missing function

**Comment by GuyKh** [comment]
@mamsterla which branch? It's already merged (and rolled out)

**Comment by mamsterla** [comment]
It’s on the branch called V3-and-Ancestry-fixes, but let me work with Jeff to get this merged into the release

**Comment by mamsterla** [comment]
👍

Jeff G reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by GuyKh** [comment]
@mamsterla - I guess you're mentioning the branch in your repo - https://github.com/mamsterla/SmartCopy/tree/v3-and-Ancestry-fixes
Please note that the PR (on that branch) is already merged so I suggest rebasing into a new branch

**Comment by stbodie** [comment]
Circling back on this one since it came up while auditing older PRs/issues for anything still outstanding.

**What it was:** right after the Manifest V3 migration (#124), `getPageCode()` in `popup.js` called `await getTabId()` to resolve the active tab's ID for `chrome.scripting.executeScript` — but `getTabId` was never actually defined, so any collection using `parseProfileData` (FindAGrave in the traceback, but this would've hit every such collection) crashed with `ReferenceError: getTabId is not defined`. Looks like an oversight from the V3 migration itself, where the old tab-resolution approach got swapped for a call to a helper that was never written.

**Current status: already fixed, nothing further needed.** `getTabId` is properly defined in current `master` (`popup.js`, commit `e6f5eea "Update getTabId"`):
```js
async function getTabId() {
    let queryOptions = { active: true, currentWindow: true };
    let tabs = await chrome.tabs.query(queryOptions);
    return tabs[0].id;
}
```
and it's correctly `await`-ed at the original crash site (`const tabId = await getTabId();`). Confirmed there's no lingering reference-error risk here — correctly closed.
